Move base64 to flamecore
It does not work on EPEL8 with gcc-8.4.1 current way, but works just
fine on Fedora's gcc-11.2.1.  flame/query.cpp uses base64_encode and
thus needs it also in flamecore already.

Without this change building of tests fails with:
libflamecore.so: undefined reference to `base64_encode[abi:cxx11](unsigned char const*, unsigned int)'